### ISSUE TITLE
Dark Mode Support

### ISSUE THREAD

**Issue by fishcharlie** [PoeticThemes/boo#15]
It'd be great if this theme supported the new CSS media query `prefers-color-scheme: dark`.

https://paulmillr.com/posts/using-dark-mode-in-css/

**Comment by fishcharlie** [comment]
I'm for sure not very good at colors and styling in CSS. But here is a **SUPER** basic first attempt at this. If anyone wants to use this as a starting point for implementing this into the project feel free. Not sure how good it is tho.

Hope to see this implemented soon!! Let me know how I can support with this.

```css
@media (prefers-color-scheme:dark) {
    .site-wrapper {
        background: #000
    }

    a {
        color: #a8a8a8
    }

    a:hover {
        color: #b5b5b5
    }

    body {
        color: #d1d1d1
    }

    h1, h2, h3, h4, h5, h6 {
        color: #e9e9e9
    }

    blockquote {
        border-left: #a8a8a8 .4em solid
    }

    .post {
        border-bottom: #191919 1px solid
    }

    .extra-pagination {
        border-bottom: #27292a 1px solid
    }

    .extra-pagination:after {
        box-shadow: #000 0 0 0 5px;
        background: #000;
        border: #27292a 1px solid
    }

    code, tt {
        background: #272828;
        border: #383c3f 1px solid
    }
}
```
